### PR TITLE
Made zenoh router runnable in launch file

### LINKED ISSUE #27: Document how to start zenoh router in launch file
```
Thank you! IMO, this explanation should be documented in the launch file. Otherwise 👍 from me
```
_Originally posted by @henningkayser in https://github.com/CihatAltiparmak/moveit_middleware_benchmark/pull/22#issuecomment-2284065749_

Note: rmw_zenoh is still in development and there is a PR to remove tty stuffs. It can be good to wait a little bit.

### PR DESCRIPTION
**Pull request by CihatAltiparmak**
With this PR, we will be able to run zenoh router in launch file. This PR provides us to work on automatizing to benchmark all middleware stuffs until zenoh router can be started implicitly inside rmw layer. I used SIGTERM to close zenoh router process, but rmw_zenoh doesn't handle SIGTERM whereas handles SIGINT. I have sent a PR for it. If it's merged, this PR will work well. Maybe it can be used SIGINT however i'm besider of SIGTERM.

### CODE REVIEW

**Comment by CihatAltiparmak** [comment]
@sjahr it can be better to review this in the your available time. Even if we don't merge this stuffs before other PRs, i t would be better to review this in the frontline before merging.

**Comment by henningkayser** [comment]
I'm sure we discussed this previously, but what is the main reason to directly call the router instead of using ExecuteProcess? https://github.com/ros2/launch/blob/rolling/launch/launch/actions/execute_process.py

**Comment by CihatAltiparmak** [comment]
Because zenoh router needs to use /dev/tty as stdin. We cannot set stdin in ExecuteProcess. the functionality of launch tool doesn't allow to set stdin, Even if we use `shell=True` parameter and set stdin using `ros2 run rmw_zenoh_cpp rmw_zenoh < /dev/tty`, launch closes process unsoundly, it somehow trigger neither the SIGTERM nor SIGINT. I could solve this using separate subprocess mechanism, which allows us to modify stdin of process directly. See my comment in this issue. ( https://github.com/ros2/rmw_zenoh/issues/206#issuecomment-2257292941 )

But i'm okay with use `ros2 run rmw_zenoh_cpp rmw_zenohd` in this PR. This time perror gives rise to ugly ending, but all of the process finishes gracefully. See my comment ( https://github.com/ros2/rmw_zenoh/pull/252#issuecomment-2259973649 )

**Comment by henningkayser** [comment]
> Because zenoh router needs to use /dev/tty as stdin. We cannot set stdin in ExecuteProcess. the functionality of launch tool doesn't allow to set stdin, Even if we use `shell=True` parameter and set stdin using `ros2 run rmw_zenoh_cpp rmw_zenoh < /dev/tty`, launch closes process unsoundly, it somehow trigger neither the SIGTERM nor SIGINT. I could solve this using separate subprocess mechanism, which allows us to modify stdin of process directly. See my comment in this issue. ( [ros2/rmw_zenoh#206 (comment)](https://github.com/ros2/rmw_zenoh/issues/206#issuecomment-2257292941) )
> 
> But i'm okay with use `ros2 run rmw_zenoh_cpp rmw_zenohd` in this PR. This time perror gives rise to ugly ending, but all of the process finishes gracefully. See my comment ( [ros2/rmw_zenoh#252 (comment)](https://github.com/ros2/rmw_zenoh/pull/252#issuecomment-2259973649) )

Thank you! IMO, this explanation should be documented in the launch file. Otherwise :+1: from me

**Comment by CihatAltiparmak** [comment]
Let's merge after #26 and #30 are merged. 
> But i'm okay with use ros2 run rmw_zenoh_cpp rmw_zenohd in this PR.

Now seems not okay with use of it :face_with_diagonal_mouth:

**Comment by CihatAltiparmak** [comment]
I'm closing this PR because some PRs about zenoh_router is solved so that tty is removed and SIGTERM handling is added. I have decided to add zenoh_router to other PRs which is addition of other scenarios.

**Pull request closed without merging**
