### PR TITLE
Feature/custom GitHub actions

### PR DESCRIPTION
**Pull request by CihatAltiparmak**

### CODE REVIEW

**Comment by CihatAltiparmak** [comment]
Hello @henningkayser , this PR is for Github actions. Could you review it when you are available? Thanks in advance.

Edit: CC @sjahr

**Comment by CihatAltiparmak** [comment]
Normaly, in this PR,  there is a few commits. Don't be frustuated! Seems it's Github relavant problem. It's enough to check out Github action relavant files.

**Review by henningkayser — DISMISSED** [review]
It's weird that GitHub shows the huge list of commits. Are you sure you don't want to rebase your changes onto main? Just reviewing the GHA jobs, I don't see anything wrong with the setup. Do you have any specific questions about it you want to discuss?

**Comment by CihatAltiparmak** [comment]
As you can see in this link( https://github.com/CihatAltiparmak/moveit_middleware_benchmark/compare/main...feature/custom_github_actions ) , there are less commits. I don't know why shows a ton of commits. Anyway i have no question at the moment. I think using merging normally instead of rebasing would be more appropriate.

  Github has dismissed your approval, not me. @henningkayser Could you give an approval again if it's still okay? I can break the rules, but i don't want.

**Review by sjahr — APPROVED** [review]
Re-Approving this for @henningkayser. @CihatAltiparmak you can merge it :+1:

**Comment by CihatAltiparmak** [comment]
Apologies, Seems github relavant bug (https://github.com/orgs/community/discussions/58535) I had to break the rules. @sjahr's approval didn't work

**Pull request merged**
